version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: parking_db
    restart: always
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
